(* D2 diagnostic: do the Private symbols resolve and apply? *)
$HistoryLength = 0;
p[args___] := Print[Row[{args}]];
Get["/Users/huyan00/mycode/SpectralElement/Kernel/SpectralElement.wl"];
PR = SpectralElement`Private;
p["1 ContextPath = ", ContextPath];
p["2 nNames = ", Length[Names[PR]]];
p["3 member seNodeVec = ", MemberQ[Names[PR], "seNodeVec"]];
p["4 member seStackOperator = ", MemberQ[Names[PR], "seStackOperator"]];
p["5 OwnValues seNodeVec = ", Length[OwnValues[PR`seNodeVec]], " DownValues = ", Length[DownValues[PR`seNodeVec]]];
p["6 seNodeVec small = ", PR`seNodeVec[{{1., 2.}, {3., 4.}}]];
p["7 Head = ", Head[PR`seNodeVec[{{1., 2.}, {3., 4.}}]]];
regR = Rectangle[{-1.5, -1.2}, {1.8, 1.3}];
disc = Quiet[SpectralElement`SpectralDomain[regR, 6]];
p["8 disc Head = ", Head[disc], " Type = ", Lookup[disc, "Type"]];
p["9 NodeCount = ", disc["NodeCount"], " IntegerQ = ", IntegerQ[disc["NodeCount"]]];
p["10 PatchOps len = ", Length[disc["PatchOps"]]];
uexd[ax_, ay_] := Sin[ax ay] + ax/3;
zex = PR`seExactGlobal[disc, uexd];
p["11 zex len = ", Length[zex], " numeric = ", VectorQ[zex, NumericQ]];
nn = disc["NodeCount"];
o1 = disc["PatchOps"][[1]];
t1 = Table[N[uexd[o1["Xs"][[ix, iy]], o1["Ys"][[ix, iy]]]], {ix, 1, nn}, {iy, 1, nn}];
p["12 t1 dims = ", Dimensions[t1], " numeric = ", VectorQ[Flatten[t1], NumericQ]];
p["13 seNodeVec t1 head = ", Head[PR`seNodeVec[t1]], " len = ", Length[PR`seNodeVec[t1]]];
A0 = PR`seStackOperator[disc, -1.];
p["14 seStackOperator Head = ", Head[A0], " Dims = ", Dimensions[A0]];
lfz = ConstantArray[0., {1, nn^2}];
gt = PR`seGather[disc, lfz, zex];
p["15 seGather Head = ", Head[gt], " Dims = ", Dimensions[gt]];
rhsS = PR`seAssembleRHS[disc, Laplacian[uexd[ax_, ay_], {ax, ay}], ax, ay];
p["16 assembleRHS len = ", Length[rhsS], " numeric = ", VectorQ[rhsS, NumericQ]];
p["DONE-d2_diag"];
