(* D2 final diagnostic.  NOTHING is Quiet-wrapped here: Quiet does not record
   into $MessageList, which is why the previous phase probe saw zero. *)
$HistoryLength = 0;
p[args___] := Print[Row[{args}]];
Get["/Users/huyan00/mycode/SpectralElement/Kernel/SpectralElement.wl"];
uexz[x_, y_] := Sin[2 x + 1] Cos[3 y - 1] + x y/5;
bdR = Abs[x + 1.5] < 1.*^-8 || Abs[x - 1.8] < 1.*^-8 || Abs[y + 1.2] < 1.*^-8 || Abs[y - 1.3] < 1.*^-8;
regR = Rectangle[{-1.5, -1.2}, {1.8, 1.3}];
fLin = -Laplacian[uexz[x, y], {x, y}];
eqLin = {-Laplacian[u[x, y], {x, y}] == fLin, DirichletCondition[u[x, y] == uexz[x, y], bdR]};
ph[tag_, expr_] := Module[{m0 = Length[$MessageList], r, ml, tg}, r = Check[expr, $Failed]; ml = $MessageList[[m0 + 1 ;; Length[$MessageList]]]; tg = Cases[ml, HoldForm[h_, ___] :> h]; p["  ", StringPad[tag, 24], " new=", Length[ml], "  tags=", tg]; r];
p["=== P1 linear Rectangle n=16, phase by phase, UNQUIETED ==="];
disc = ph["SpectralDomain", SpectralElement`SpectralDomain[regR, 16]];
parts = ph["seOperatorParts", SpectralElement`Private`seOperatorParts[eqLin, u, {x, y}]];
dc = ph["seDirConditions", SpectralElement`Private`seDirConditions[eqLin, u, {x, y}]];
lfFn = ph["seDirLiftFn", SpectralElement`Private`seDirLiftFn[dc, x, y]];
lf = ph["seLiftFrom", SpectralElement`Private`seLiftFrom[disc, lfFn]];
A0 = ph["seStackOperator", SpectralElement`Private`seStackOperator[disc, -1.]];
c0 = ph["seLiftConst", SpectralElement`Private`seLiftConst[disc, -1., lf]];
rhs = ph["seAssembleRHS", SpectralElement`Private`seAssembleRHS[disc, fLin, x, y]];
z = ph["seLinSolve", SpectralElement`Private`seLinSolve[A0, rhs - c0]];
fnv = ph["seSolutionFn", SpectralElement`Private`seSolutionFn[disc, z, lf]];
p["=== the public call at n=16 (seEnsureDisc is quiet internally) ==="];
r16 = ph["SpectralNDSolve n16", SpectralElement`SpectralNDSolve[eqLin, u, {x, y} \[Element] regR, 16]];
i16 = SpectralElement`Private`seLastSolve;
p["  ok=", Lookup[i16, "Ok"], " reason=", Lookup[i16, "Reason"]];
p["=== G12: reuse of a PRE-BUILT discretization ==="];
dPre = Check[SpectralElement`SpectralDomain[regR, 16], $Failed];
p["  dPre Q = ", SpectralElement`SpectralDomainQ[dPre], " degree=", Lookup[dPre, "Degree"]];
rRe = ph["SpectralNDSolve on dPre", SpectralElement`SpectralNDSolve[eqLin, u, {x, y} \[Element] dPre, 16]];
iRe = SpectralElement`Private`seLastSolve;
p["  ok=", Lookup[iRe, "Ok"], " reason=", Lookup[iRe, "Reason"], " regionQ=", SpectralElement`SpectralDomainQ[Lookup[iRe, "Region"]]];
p["=== G10: capped Newton, and the EXACT shape of a tagged $MessageList entry ==="];
m0 = Length[$MessageList];
rFail = SpectralElement`SpectralNDSolve[{-Laplacian[u[x, y], {x, y}] + u[x, y]^3 == fLin + uexz[x, y]^3, DirichletCondition[u[x, y] == uexz[x, y], bdR]}, u, {x, y} \[Element] regR, 16, MaxIterations -> 1, Tolerance -> 1.*^-30];
ml = $MessageList[[m0 + 1 ;; Length[$MessageList]]];
p["  Head[rFail]=", Head[rFail], "  newMsgs=", Length[ml]];
Do[p["   [", i, "] FullForm: ", ToString[ml[[i]], FullForm]], {i, 1, Length[ml]}];
p["  tags via Cases = ", Cases[ml, HoldForm[h_, ___] :> h]];
p["=== G11: no PDE at all ==="];
m0 = Length[$MessageList];
rN = SpectralElement`SpectralNDSolve[{DirichletCondition[u[x, y] == uexz[x, y], bdR]}, u, {x, y} \[Element] regR, 16];
ml = $MessageList[[m0 + 1 ;; Length[$MessageList]]];
p["  Head[rN]=", Head[rN], "  newMsgs=", Length[ml], "  tags=", Cases[ml, HoldForm[h_, ___] :> h]];
p["DONE-d2_final"];
