$HistoryLength = 0;
p[args___] := Print[Row[{args}]];
Get["/Users/huyan00/mycode/SpectralElement/Kernel/SpectralElement.wl"];
uexz[x_, y_] := Sin[2 x + 1] Cos[3 y - 1] + x y/5;
bdR = Abs[x + 1.5] < 1.*^-8 || Abs[x - 1.8] < 1.*^-8 || Abs[y + 1.2] < 1.*^-8 || Abs[y - 1.3] < 1.*^-8;
regR = Rectangle[{-1.5, -1.2}, {1.8, 1.3}];
eq = {-Laplacian[u[x, y], {x, y}] == -Laplacian[uexz[x, y], {x, y}], DirichletCondition[u[x, y] == uexz[x, y], bdR]};
res = SpectralElement`SpectralNDSolve[eq, u, {x, y} \[Element] regR, 8];
info = SpectralElement`Private`seLastSolve;
disc = Lookup[info, "Disc"];
ops = Lookup[disc, "PatchOps"];
pc = Lookup[disc, "PatchCount"];
nn = Lookup[disc, "NodeCount"];
o1 = ops[[1]];
xga = o1["Nodes1D"];
g = SpectralElement`Private`seGather[disc, Lookup[Lookup[info, "Parts"], "Lift"], Lookup[info, "Global"]];
Uv = g;
maps = {}; Jf = {}; pts = {};
Do[maps = Append[maps, Lookup[Lookup[ops[[q]], "Patch"], "Map"]]; Dm = ops[[q]]["Dm"]; Xg = ops[[q]]["Xs"]; Yg = ops[[q]]["Ys"]; Jf = Append[Jf, {{Dm.Xg, Xg.Transpose[Dm]}, {Dm.Yg, Yg.Transpose[Dm]}}]; Do[pts = Append[pts, {{N[Xg[[ix, iy]]], N[Yg[[ix, iy]]]}, q, ix, iy}], {iy, 1, nn}, {ix, 1, nn}], {q, 1, pc}];
p["A ops keys of patch1 = ", Keys[ops[[1]]]];
p["B has Patch key = ", MemberQ[Keys[ops[[1]]], "Patch"], "  map head = ", Head[maps[[1]]], "  len pts = ", Length[pts], "  Uv dims = ", Dimensions[Uv]];
X1 = N[o1["Xs"][[3, 4]]]; Y1 = N[o1["Ys"][[3, 4]]];
d2 = Table[(pts[[j, 1, 1]] - X1)^2 + (pts[[j, 1, 2]] - Y1)^2, {j, 1, Length[pts]}];
k = Ordering[d2, 1][[1]];
p["C k = ", k, " node = ", N[pts[[k, 1]]], " (patch,ix,iy) = ", N[Part[pts[[k]], 2 ;; 4]]];
r = SpectralElement`Private`seRefInverse[maps, Jf, pts, xga, k, X1, Y1];
p["D refInverse = ", N[r], "   head = ", Head[r]];
p["E xi numericQ = ", TrueQ[NumericQ[Part[r, 2]]], " eta numericQ = ", TrueQ[NumericQ[Part[r, 3]]], " xi = ", N[Part[r, 2]], " eta = ", N[Part[r, 3]]];

p["DONE-p1c"];
fn = res[[1, 1, 2]];
ptsTab = Table[N[fn[N[o1["Xs"][[ix, iy]]], N[o1["Ys"][[ix, iy]]]]], {ix, 1, nn}, {iy, 1, nn}];
nodTab = Table[Part[Uv[[1]], ix + (iy - 1) nn], {ix, 1, nn}, {iy, 1, nn}];
exTab = Table[N[uexz[N[o1["Xs"][[ix, iy]]], N[o1["Ys"][[ix, iy]]]]], {ix, 1, nn}, {iy, 1, nn}];
p["I NODE REPRODUCTION  max |u(node) - nodal| = ", N[Max[Abs[Flatten[ptsTab] - Flatten[nodTab]]]]];
p["J NODE ACCURACY      max |u(node) - exact| = ", N[Max[Abs[Flatten[ptsTab] - Flatten[exTab]]]]];
Xn = N[(o1["Xs"][[3, 4]] + o1["Xs"][[4, 5]])/2]; Yn = N[(o1["Ys"][[3, 4]] + o1["Ys"][[4, 5]])/2];
p["K1 off-node midpoint  u = ", N[fn[Xn, Yn]], "   exact ", N[uexz[Xn, Yn]], "   allNumeric = ", TrueQ[VectorQ[{fn[Xn, Yn]}, NumericQ]]];
p["K2 far outside (9,9)  u = ", N[fn[9., 9.]]];
mid2 = Table[N[fn[N[(o1["Xs"][[ix, iy]] + o1["Xs"][[ix + 1, iy]])/2], N[(o1["Ys"][[ix, iy]] + o1["Ys"][[ix + 1, iy]])/2]]], {ix, 1, nn - 1}, {iy, 1, nn}];
p["K3 all mid-edge points numeric = ", TrueQ[VectorQ[Flatten[mid2], NumericQ]], "   n = ", Length[Flatten[mid2]]];
p["DONE-p1c"];